services:
  db1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nospecify
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3309:3306"

  app1:
    image: mapp:latest
    environment:
      MYSQL_HOST: db1
      MYSQL_DATABASE: nospecify
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      SERVICE_PORT: 8080
    depends_on:
      - db1
    ports:
      - "8083:8080"

  app2:
    image: napp:latest
    environment:
      MYSQL_HOST: db1
      MYSQL_DATABASE: nospecify
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      SERVICE_PORT: 8085
    depends_on:
      - db1
    ports:
      - "8085:8080"
